### ISSUE TITLE
Problems when URL already contains some query string

### ISSUE THREAD

**Issue by ghost** [rafapaulino/PHP-Pagination#1]
> Sorry for my English

When the address bar already contains some query string with the specified method for obtaining the link, the current method resets other values, setting only the page values.

For example for a page:
`/category?show=20&sort=price`

a link will be generated:
`/category?price=5`

I fixed it in the following way, and I think that this functionality should be taken into account and is available by default. I created a function:

```
function paginationLink($number){
    if (strpos($_SERVER['REQUEST_URI'], '?') !== false) {
        if (isset($_GET['page'])) {
            if (strpos($_SERVER['REQUEST_URI'], '?page=') !== false) {
                return str_replace('?page=' . $_GET['page'], '?page=' . $number, $_SERVER['REQUEST_URI']);
            }
            if (strpos($_SERVER['REQUEST_URI'], '&page=') !== false) {
                return str_replace('&page=' . $_GET['page'], '&page=' . $number, $_SERVER['REQUEST_URI']);
            }
        } else {
            return $_SERVER['REQUEST_URI'] . '&page=' . $number;
        }
    } else {
        return $_SERVER['REQUEST_URI'] . '?page=' . $number;
    }
}
```

And I call it in every link, passing various methods:

```
<a class="page-link" href="<?php echo paginationLink($pagination->getFirstPage()); ?>">
...
<a class="page-link" href="<?php echo paginationLink($iterator->current()); ?>">
```

Then the link on the page:
`/category?show=20&sort=price`

it will look like:
`/category?show=20&sort=price&page=5`

Perhaps you will make everything more beautiful.

**Comment by rafapaulino** [comment]
> > Sorry for my English
> 
> When the address bar already contains some query string with the specified method for obtaining the link, the current method resets other values, setting only the page values.
> 
> For example for a page:
> `/category?show=20&sort=price`
> 
> a link will be generated:
> `/category?price=5`
> 
> I fixed it in the following way, and I think that this functionality should be taken into account and is available by default. I created a function:
> 
> ```
> function paginationLink($number){
>     if (strpos($_SERVER['REQUEST_URI'], '?') !== false) {
>         if (isset($_GET['page'])) {
>             if (strpos($_SERVER['REQUEST_URI'], '?page=') !== false) {
>                 return str_replace('?page=' . $_GET['page'], '?page=' . $number, $_SERVER['REQUEST_URI']);
>             }
>             if (strpos($_SERVER['REQUEST_URI'], '&page=') !== false) {
>                 return str_replace('&page=' . $_GET['page'], '&page=' . $number, $_SERVER['REQUEST_URI']);
>             }
>         } else {
>             return $_SERVER['REQUEST_URI'] . '&page=' . $number;
>         }
>     } else {
>         return $_SERVER['REQUEST_URI'] . '?page=' . $number;
>     }
> }
> ```
> 
> And I call it in every link, passing various methods:
> 
> ```
> <a class="page-link" href="<?php echo paginationLink($pagination->getFirstPage()); ?>">
> ...
> <a class="page-link" href="<?php echo paginationLink($iterator->current()); ?>">
> ```
> 
> Then the link on the page:
> `/category?show=20&sort=price`
> 
> it will look like:
> `/category?show=20&sort=price&page=5`
> 
> Perhaps you will make everything more beautiful.



Hi! Sorry for the delay to reply!
From what I understand the problem is that you need to generate the url with all the parameters.

I believe you need to generate a base url:
https://stackoverflow.com/questions/17201170/php-how-to-get-the-base-domain-url/17201261

From the base URL you can generate the other parameters, for example:

**base_url . '?page=' . $page . '&category=' . $category;**
